Fix/redirect validator
opengovsg/isomer pull request #478
Opened 2024-08-15 01:41 UTC by alexanderleegs

See [thread](https://opengovproducts.slack.com/archives/CK9GGK6EP/p1722841650033399). This PR modifies our redirect url validation.

2024-08-15 07:28 UTC, karrui requested changes
@alexanderleegs can help change the directory of the installed package to studio?

2024-08-15 07:28 UTC, karrui commented on package.json
since this is a monorepo, i think the package should be installed in the correct package!

2024-08-15 08:17 UTC, alexanderleegs commented on package.json
whoops, fixed in https://github.com/opengovsg/isomer/pull/478/commits/05bb46285bb68e020a68255e8359d948cdfa9a7e

2024-08-16 02:32 UTC, karrui approved these changes
lgtm

2024-08-16 02:32 UTC, merged