isom-1651 - add acceptable file type messages
opengovsg/isomer pull request #846
Opened 2024-10-29 08:30 UTC by adriangohjw

## Problem

Closes https://linear.app/ogp/issue/ISOM-1651/inform-users-that-only-pdfs-are-supported

## Solution

**Breaking Changes**

- [ ] Yes - this PR contains breaking changes
  - Details ...
- [x] No - this PR is backwards compatible

**Improvements**:

- add a copywriting text

**AFTER**:

<img width="652" alt="image" src="https://github.com/user-attachments/assets/c6fd3a69-9bdc-4b99-845a-d1330a8b6e41">

2024-10-29 09:40 UTC, sehyunidaaa commented
@adriangohjw I'm okay with this, thanks for taking a shot at it! My only concern is that the text at the bottom sometimes gets replaced by the error message. Example screenshot attached!

Currently the error message for unspported file extension reads: 
"Your file's extension ending in {extension} is not allowed" 
And it's not too clear what I did wrong.

Should we change the error message for unsupported file extensions to be more instructive:
"For security reasons, only .pdf files are accepted. Please upload a .pdf file." 

![image](https://github.com/user-attachments/assets/c27cec8b-5143-4bec-90a0-a2fd378a6bad)

2024-10-29 09:40 UTC, sehyunidaaa requested changes
Left a comment re: error message

2024-10-29 09:44 UTC, adriangohjw commented
@sehyunidaaa unfortunately that's not possible with OGPDS too 😢 
https://design.open.gov.sg/?path=/docs/components-attachment--docs

2024-10-29 09:50 UTC, sehyunidaaa commented
@adriangohjw gooosh okay :( i'm good with this workaround!

2024-10-29 09:50 UTC, sehyunidaaa approved these changes

2024-10-30 02:51 UTC, harishv7 approved these changes

2024-10-30 03:22 UTC, merged